---
new_page_extension: md
auto_deploy: true
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/post
  label: News Posts
  create: all
  match: "**/*"
- type: heading
  label: "\U0001F387 Photo"
- type: directory
  path: content/collections
  label: Collections
  create: all
  match: "**/*"
  templates:
  - collection-page-builder
- type: document
  path: data/categories/categories.toml
  label: Categories
upload_dir: static/uploads
public_path: https://jesserieser.brandlew.co/uploads
front_matter_path: uploads
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.56.0
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build:forestry
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.2
  output_directory: public
  preview_command: npm run build:forestry
version: 0.55.2
